### ISSUE TITLE
Are coordinates in decimeters or meters

### ISSUE THREAD

**Issue by zhlstone** [gnns4hri/sngnn1dv2#2]
I'm not sure if the data is labeled in meters or decimeters. I find that in socnav.py  the position is computed by xpos = h['x'] / 10.         ypos = h['y'] / 10 in line 201-202, but i check the data that seems to be labeled in meters.

**Comment by vangiel** [comment]
Hello zhlstone, thanks for your question. The data is in meters. However, while creating the graph, the coordinates are divided by 10 to normalize it for the network.
